# Generated by Django 6.0.2 on 2026-03-01 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_vault'),
    ]

    operations = [
        migrations.AddField(
            model_name='vault',
            name='item_count',
            field=models.IntegerField(default=0),
        ),
    ]
