# Generated by Django 6.0.2 on 2026-03-01 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_executor_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='recipient',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
    ]
