# Generated by Django 6.0.2 on 2026-03-01 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_executor_is_verified_alter_executor_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='executor',
            name='verification_document',
            field=models.FileField(blank=True, null=True, upload_to='verification_docs/'),
        ),
    ]
